package com.jamestaeil.hrerp.platform.authorization;

public enum PermissionCode {
	PLATFORM_AUTHORIZATION_MANAGE,
	PLATFORM_ORGANIZATION_MANAGE,
	PLATFORM_REFERENCE_MANAGE,
	HR_EMPLOYEE_REGISTER,
	HR_RECORD_READ,
	HR_RECORD_WRITE,
	HR_LIFECYCLE_READ,
	HR_LIFECYCLE_WRITE,
	HR_RECORD_SENSITIVE_READ,
	PAYROLL_CONFIRM,
	FILING_CONFIRM
}
