INSERT INTO platform_permissions (permission_code, sensitive_operation) VALUES
    ('PLATFORM_AUTHORIZATION_MANAGE', TRUE),
    ('HR_EMPLOYEE_REGISTER', FALSE),
    ('HR_RECORD_READ', FALSE),
    ('HR_RECORD_WRITE', FALSE),
    ('HR_LIFECYCLE_READ', FALSE),
    ('HR_LIFECYCLE_WRITE', FALSE),
    ('HR_RECORD_SENSITIVE_READ', TRUE),
    ('PAYROLL_CONFIRM', TRUE),
    ('FILING_CONFIRM', TRUE);
